### ISSUE TITLE
Globally installed NPM is not used when running with download=false

### ISSUE THREAD

**Issue by legaev-stas** [srs/gradle-node-plugin#64]
Hello,
I'm trying to run my gradle-node-plugin with such configuration:
node {
    download = false
}
I assume globally installed Node and NPM will be used. But I see such exception:
:project:nodeSetup SKIPPED
:project:npmSetup SKIPPED
:project:npmInstall
module.js:338
    throw err;
          ^
Error: Cannot find module 'D:\project\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
:project:npmInstall FAILED

FAILURE: Build failed with an exception.

Seems path to NPM is hardcoded to %wordingDir%\node_modules\npm\bin\npm-cli.js

**Comment by Vistritium** [comment]
I also have this issue.

**Comment by cmnzs** [comment]
I also seem to have this issue after updating to 0.10. Any workarounds?

**Comment by shawmanz32na** [comment]
I'll +1 this - I'm having the same issue.

**Comment by et0s** [comment]
I'm having the same issue, is there a workaround for this yet?

**Comment by srs** [comment]
You can try to set npmCommand = 'npm' to see if that works.

     node {
       npmCommand = 'npm'
     }

**Comment by StephenTurley** [comment]
I'm having the same issue. 

Cannot find module 'D:\Projects\ ... \node_modules\npm\bin\npm-cli.js'

Rolling back to version 0.9 fixes the issue. Seems to be a regression.

Tried using: node {
   npmCommand = 'npm'
 }
and it made no difference.

**Comment by srs** [comment]
Thanks. Will take a look at this in the comming weekend.

On Fri, Nov 20, 2015 at 12:56 AM, Stephen Turley <notifications@github.com>
wrote:

> I'm having the same issue.
>
> Cannot find module 'D:\Projects\ ... \node_modules\npm\bin\npm-cli.js'
>
> Rolling back to version 0.9 fixes the issue. Seems to be a regression.
>
> Tried using: node {
> npmCommand = 'npm'
> }
> and it made no difference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/srs/gradle-node-plugin/issues/64#issuecomment-158237814>
> .
>



-- 
Vennlig hilsen/Best regards

Sten Roger Sandvik
Development Manager
+47 95997084

The fastest way from idea to Digital Experience -
http://youtu.be/cFfxuWUgcvI

**Comment by qgicup** [comment]
I'm having the same issue. Any updates on it?

**Comment by drbignik** [comment]
Same issue here. Waiting for this to be resolved.

**Comment by srs** [comment]
Forgot to reply on the status. Yes, I think I have the fix and will be
adding it into the next version. I will try to make a new release within a
couple of days.

On Fri, Jan 8, 2016 at 1:52 PM, Nikita Kurpas <notifications@github.com>
wrote:

> Same issue here. Waiting for this to be resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/srs/gradle-node-plugin/issues/64#issuecomment-169992196>
> .
>



-- 
Vennlig hilsen/Best regards

Sten Roger Sandvik
Development Manager
+47 95997084

The fastest way from idea to Digital Experience -
http://youtu.be/cFfxuWUgcvI

**Comment by karlderkaefer** [comment]
if you run npmInstall task on windows with --info you will see that it calls [cmd /c ""npm" "install"]. You will get same message if you type directly in commandline ["npm" "install"]. So it may work if the plugin calls [cmd /c "npm install"]

**Comment by mborman** [comment]
Not to add a "Me too"... but I confirmed that downgrading to version 0.9 as suggested by @StephenTurley _does_ fix the issue for me as well. I am on Windows.

**Comment by karlderkaefer** [comment]
it works with local build 0.12-SNAPSHOT. any news on release of 0.12?

**Comment by shawmanz32na** [comment]
I'll "Me too" this, since I've been experiencing this issue for months and am waiting on the fix staged for 0.12. What's the good word on the release of 0.12? Coming soon?

**Comment by srs** [comment]
I am trying to get 0.12 out within the weekend.

**Comment by ikomangmahendra** [comment]
Got this issue, waiting for this to be resolved.

**Comment by sagarpatil232** [comment]
Me too having this issue.

**Comment by srs** [comment]
Closing this since it seems to work on 0.12 and later.
