### ISSUE TITLE
v0.10 nodeModulesDir does work

### ISSUE THREAD

**Issue by stevematyas** [srs/gradle-node-plugin#59]
```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath('com.moowork.gradle:gradle-node-plugin:0.10')
        classpath('com.moowork.gradle:gradle-grunt-plugin:0.6')
    }
}

apply plugin: 'com.moowork.node'
apply plugin: 'grunt'

node {
    // Version of node to use.
    version = '0.10.33'

    // Version of npm to use.
    npmVersion = '2.1.12'

    // Base URL for fetching node distributions (change if you have a mirror).
    distBaseUrl = 'http://nodejs.org/dist'

    // If true, it will download node using above parameters.
    // If false, it will try to use globally installed node.
    download = true

    // Set the work directory for unpacking node
    workDir = file("${project.buildDir}/nodejs")

    // Set the work directory where node_modules should be located
// not available in 0.9
    nodeModulesDir = file("${project.projectDir}/foo")
}
```

```sh
ls -a foo/
.	..
```

**Comment by srs** [comment]
Sorry about this. You are right, it's not working correctly. Will see what needs to be done to fix this. 

Thanks for your bug report.

**Comment by lex-em** [comment]
Hi, what status of this problem? I'm trying to use external node and get this error:
Error: Cannot find module ‘d:\projects\test\src\main\webapp\client\node_modules\npm\bin\npm-cli.js’

**Comment by lex-em** [comment]
Does it means that plugin do not use node->nodeModulesDir ?

**Comment by lex-em** [comment]
Does it posible to change behavior of NpmTask? Can it use node->nodeModulesDir as npm home dir and NpmTask's workingDir as project working dir, which contains package.json?

**Comment by lex-em** [comment]
Or add node->npmHome variable and use node->nodeModulesDir as directory for installing modules from package.json?

**Comment by Scuilion** [comment]
I'm experiencing the same problem. 

0.9 works find. Upgrade to 0.10 and it starts looking for npm-cli.js in the wrong place.

**Comment by tarcon** [comment]
Still not working in 0.11

**Comment by kanadakid** [comment]
I ran into this problem today too. Is there any estimate on what version it might be addressed?

**Comment by kpage** [comment]
This issue has been bugging me for a while, so I started using a symlink workaround to relocate node_modules to the home directory without having to configure gradle-node-plugin.  Maybe this would help some of you as well.  This saves a lot of time on CI, because previously everything in node_modules had to be re-downloaded and installed every build (which added 1 minute to a 15 second build).

Right now this workaround creates a whole new node_modules directory each time package.json changes, so it might not be suitable if you frequently change package.json.  It also assumes that your project name is a valid directory name and requires java 7+.

It works well on OS X and Linux, but creating the symlink on Windows runs into permissions issues.  If you open your Windows terminal as Administrator terminal or configure your user's permissions to allow symlink creation, it may work.  If your Windows user doesn't have permission to create symlinks, it will fall back to creating the real node_modules directory as usual.

```groovy
// requires java 7+ due to use of java.nio
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.security.MessageDigest

def calcSha1(File f) {
    MessageDigest md = MessageDigest.getInstance("SHA-1");
    f.eachByte 4096, {bytes, size ->
        md.update(bytes, 0, size);
    }
    return md.digest().collect {String.format "%02x", it}.join();
}

    // * If node_modules does not exist, a node_modules symlink will be created
    // * If a node_modules symlink exists but package.json has changed, the link will be updated to a new node_modules folder in the user home directory
    // * If a real node_modules folder exists, it will be left alone
    task linkNodeModulesDir << {
        def link = Paths.get("${project.projectDir}/node_modules") 
        def packageJsonFile = file("package.json")
        if (packageJsonFile.exists()) {
            def packageJsonSha1 = calcSha1(packageJsonFile)
            def userHome = System.getProperty("user.home")
            def nodeModulesDirStr = "${userHome}/.gradle/node_modules_cache/${project.name}/${packageJsonSha1}/node_modules"
            def target = Paths.get(nodeModulesDirStr)
            if (Files.isSymbolicLink(link)) {
                def oldLinkTarget = Files.readSymbolicLink(link)
                if (oldLinkTarget != target) {
                    // target changed, delete old link.  npmInstall will detect that it is out-of-date because the node_modules file is 
                    // different.  When npmInstall runs, it will ensure that all package are installed in the newly-linked node_modules dir.
                    Files.deleteIfExists(link)
                }
            }
            if (!file(link.toString()).exists()) {
                def nodeModulesDir = file(nodeModulesDirStr)
                // ensure that the cached node_modules dir exists in the home directory
                if (!nodeModulesDir.exists()) {
                    mkdir nodeModulesDir
                }
                try {
                    Files.createSymbolicLink(link, target)
                } catch (Exception e) {
                    // On Windows, creating symbolic links requires permission configuration.  See: http://stackoverflow.com/a/24353758
                    logger.error('Unable to create symbolic link to node_modules.  Using a real node_modules folder instead.')
                }
                // Sometimes npmInstall will decide it is UP-TO-DATE even though node_modules has changed from e.g. a real directory to a
                // symbolic link, and then the newly-linked node_modules will not be populated correctly
                tasks.npmInstall.outputs.upToDateWhen { false } 
            }
        }
    }
    tasks.npmInstall.dependsOn linkNodeModulesDir
```

**Comment by Woodham** [comment]
It seems to me that the issue here is that `NpmTask` doesn't by itself set the workingdir (and inputs and outputs) in the same way that `NpmInstallTask` does.

`NpmInstallTask` does this which makes it work.

    this.project.afterEvaluate {
        getInputs().file( new File( (File) this.project.node.nodeModulesDir, 'package.json' ) )
        getOutputs().dir( new File( (File) this.project.node.nodeModulesDir, 'node_modules' ) )
        setWorkingDir( this.project.node.nodeModulesDir )
    }

Adding these lines to my custom task seems to make it work properly. E.g.

```
 task buildFrontend(type: NpmTask) {

    this.project.afterEvaluate {
        getInputs().file( new File( (File) this.project.node.nodeModulesDir, 'package.json' ) )
        getOutputs().dir( new File( (File) this.project.node.nodeModulesDir, 'node_modules' ) )
        setWorkingDir( this.project.node.nodeModulesDir )
    }

    args = ['run-script', 'dev-build']
}
```

(Note: You may also want to add more inputs/outputs here depending on your task so that gradle actually runs it when you want it to..)

**Comment by scorpfrog** [comment]
Thanks for the comment Woodham. I have tried your fix to set the node_modules and package.json paths pointing to another directory but when I run npm_install it still searches in the project directory.

**Comment by srs** [comment]
This is now fixed in #107 and will be available in version 0.13.
