### ISSUE TITLE
What went wrong: com/moowork/gradle/node/NodePlugin

### ISSUE THREAD

**Issue by markewallace** [srs/gradle-node-plugin#100]
Hi

I have just followed the instructions to try this plugin and I'm seeing the error below:

```
15:55:00.809 [ERROR] [org.gradle.BuildExceptionReporter] 
15:55:00.811 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:55:00.812 [ERROR] [org.gradle.BuildExceptionReporter] 
15:55:00.813 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:55:00.813 [ERROR] [org.gradle.BuildExceptionReporter] com/moowork/gradle/node/NodePlugin
15:55:00.813 [ERROR] [org.gradle.BuildExceptionReporter] > com.moowork.gradle.node.NodePlugin
15:55:00.814 [ERROR] [org.gradle.BuildExceptionReporter] 
15:55:00.814 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:55:00.814 [ERROR] [org.gradle.BuildExceptionReporter] java.lang.NoClassDefFoundError: com/moowork/gradle/node/NodePlugin
15:55:00.815 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.moowork.gradle.grunt.GruntPlugin.apply(GruntPlugin.groovy:16)
15:55:00.815 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.moowork.gradle.grunt.GruntPlugin.apply(GruntPlugin.groovy)
15:55:00
```

My gradle build file has the following:
```
buildscript {
  repositories {
    maven {
      url 'https://plugins.gradle.org/m2/'
    }
  }
  dependencies {
    classpath 'com.moowork.gradle:gradle-grunt-plugin:0.12'
  }
}

plugins {
  id 'com.moowork.grunt' version '0.12'
}

apply plugin: 'maven-publish'
apply plugin: 'osgi'
apply plugin: 'java'
apply plugin: 'com.moowork.grunt'
```

Any pointers on what I've done wrong?

thanks
Mark

**Comment by srs** [comment]
I got the same error some days ago. It seems that you need to add the node plugin too.

    buildscript {
      repositories {
        maven {
          url 'https://plugins.gradle.org/m2/'
        }
      }
      dependencies {
        classpath 'com.moowork.gradle:gradle-node-plugin:0.12'
        classpath 'com.moowork.gradle:gradle-grunt-plugin:0.12'
      }
    }

I do not know what's causing this, but it's not always so. Will fix this in the next version.

**Comment by markewallace** [comment]
Thanks Sten, that resolved my issue

**Comment by mmikhulya** [comment]
I got the same error when upgrading from 0.11 to 0.12.
Adding dependency to node solve issue with `ClassNotFoundException`, but leads to another exception:
```
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method classpath() for arguments [com.moowork.gradle:gradle-node-plugin:0.12]
```

Is it possible to fix the root of issue?
I believe issue shouldn't be closed if only workaround exists.
Also now plugin doesn't work as described in documentation (https://github.com/srs/gradle-grunt-plugin).
